FROM debian:11-slim

ARG DEBIAN_FRONTEND=noninteractive

ARG LANG_ARG
ARG TIMEZONE_ARG
ARG MINETEST_VERSION_ARG
ARG IRRLICHT_VERSION_ARG
ARG MINECLONE2_VERSION_ARG

ENV LANG=$LANG_ARG
ENV TIMEZONE=$TIMEZONE_ARG
ENV MINETEST_VERSION=$MINETEST_VERSION_ARG
ENV IRRLICHT_VERSION=$IRRLICHT_VERSION_ARG
ENV MINECLONE2_VERSION=$MINECLONE2_VERSION_ARG

RUN apt-get update && \
  apt-get upgrade -y

RUN apt-get install -y locales && \
  sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen && \
  dpkg-reconfigure locales && \
  update-locale LANG=$LANG

RUN apt-get install -y tzdata && \ 
  ln -sf "/usr/share/zoneinfo/$TIMEZONE" /etc/localtime && \
  dpkg-reconfigure tzdata

RUN apt-get install -y \
  ca-certificates \
  lsb-release \
  curl \
  git \
  sed \
  --no-install-recommends
  
RUN apt-get install -y \
  g++ \
  make \
  libc6-dev \
  cmake \
  libpng-dev \
  libjpeg-dev \
  libxi-dev \
  libgl1-mesa-dev \
  libsqlite3-dev \
  libogg-dev \
  libvorbis-dev \
  libopenal-dev \
  libcurl4-gnutls-dev \
  libfreetype6-dev \
  zlib1g-dev \
  libgmp-dev \
  libjsoncpp-dev \
  libzstd-dev \
  libluajit-5.1-dev \
  --no-install-recommends
  
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*

RUN mkdir /srv/minetest

RUN useradd minetest -r -d /srv/privacyidea -s /bin/bash
RUN chown minetest:minetest /srv/minetest

USER minetest
WORKDIR /srv/minetest

RUN git clone https://github.com/minetest/minetest.git application && \
  cd application && \
  git checkout $MINETEST_VERSION
RUN git clone https://github.com/minetest/irrlicht.git application/lib/irrlichtmt && \
  cd application/lib/irrlichtmt && \
  git checkout $IRRLICHT_VERSION
RUN git clone https://git.minetest.land/MineClone2/MineClone2.git application/games/mineclone2 && \
  cd application/games/mineclone2 && \
  git checkout $MINECLONE2_VERSION

RUN mkdir /srv/minetest/data

WORKDIR /srv/minetest/application

RUN cmake . -DRUN_IN_PLACE=TRUE \
  -DBUILD_SERVER=TRUE \
  -DBUILD_CLIENT=FALSE \
  -DIRRLICHT_INCLUDE_DIR=lib/irrlichtmt/include/
  
RUN make -j$(nproc)

USER root

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

USER minetest

EXPOSE 30000/udp 30000/tcp
VOLUME /srv/minetest/data

ENTRYPOINT /entrypoint.sh
