name: Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build images
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
            arch: amd64
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract tags and labels for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            openhv/server
            ghcr.io/${{ github.repository }}

      - name: Build ${{ matrix.arch }} image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: ${{ matrix.platform }}
          tags: ${{ steps.meta.outputs.tags }}-${{ matrix.arch }}
          labels: ${{ steps.meta.outputs.labels }}

  combine:
    name: Combine platforms
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract tags and labels for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          openhv/server
          ghcr.io/${{ github.repository }}

    - name: Create manifest and push
      run: |
        for tag in $(echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'); do
          docker manifest create $tag \
            --amend $tag-amd64 \
            --amend $tag-arm64
          docker manifest push $tag
        done